const mongoose = require('mongoose');
const Substance = require('../models/Substance');
require('dotenv').config({ path: __dirname + '/../.env' });

const substances = [

    // ── Gen 1 — Elements (9 base elements, given at game start) ──────────────
    {
        substanceKey: 'hydrogen',
        type: 'element',
        name: 'Hydrogen',
        symbol: 'H',
        formula: 'H',
        category: 'base_matter',
        generationTier: 1,
        unlockTier: 0,
        baseEnergy: 1,
        stabilityFactor: 0.8,
        reactivity: 0.9,
        fantasyWeight: 2,
        color: '#FFFFFF',
        isBaseElement: true,
        isActive: true
    },
    {
        substanceKey: 'oxygen',
        type: 'element',
        name: 'Oxygen',
        symbol: 'O',
        formula: 'O',
        category: 'base_matter',
        generationTier: 1,
        unlockTier: 0,
        baseEnergy: 2,
        stabilityFactor: 0.9,
        reactivity: 0.8,
        fantasyWeight: 2,
        color: '#FF6B6B',
        isBaseElement: true,
        isActive: true
    },
    {
        substanceKey: 'carbon',
        type: 'element',
        name: 'Carbon',
        symbol: 'C',
        formula: 'C',
        category: 'base_matter',
        generationTier: 1,
        unlockTier: 1,
        baseEnergy: 3,
        stabilityFactor: 0.95,
        reactivity: 0.7,
        fantasyWeight: 3,
        color: '#2E2E2E',
        hintText: 'The backbone of diamond, steel, graphene, and impossible structures.',
        isBaseElement: true,
        isActive: true
    },
    {
        substanceKey: 'nitrogen',
        type: 'element',
        name: 'Nitrogen',
        symbol: 'N',
        formula: 'N',
        category: 'base_matter',
        generationTier: 1,
        unlockTier: 0,
        baseEnergy: 2,
        stabilityFactor: 0.97,
        reactivity: 0.3,
        fantasyWeight: 2,
        color: '#6BA3FF',
        isBaseElement: true,
        isActive: true
    },
    {
        substanceKey: 'helium',
        type: 'element',
        name: 'Helium',
        symbol: 'He',
        formula: 'He',
        category: 'base_matter',
        generationTier: 1,
        unlockTier: 3,
        baseEnergy: 5,
        stabilityFactor: 1.0,
        reactivity: 0.0,
        fantasyWeight: 3,
        color: '#FFD700',
        hintText: 'Inert. Noble. Patient.',
        isBaseElement: true,
        isActive: true
    },
    {
        substanceKey: 'sodium',
        type: 'element',
        name: 'Sodium',
        symbol: 'Na',
        formula: 'Na',
        category: 'base_matter',
        generationTier: 1,
        unlockTier: 1,
        baseEnergy: 3,
        stabilityFactor: 0.65,
        reactivity: 0.85,
        fantasyWeight: 2,
        color: '#C8C8C8',
        isBaseElement: true,
        isActive: true
    },
    {
        substanceKey: 'chlorine',
        type: 'element',
        name: 'Chlorine',
        symbol: 'Cl',
        formula: 'Cl',
        category: 'base_matter',
        generationTier: 1,
        unlockTier: 1,
        baseEnergy: 2,
        stabilityFactor: 0.7,
        reactivity: 0.9,
        fantasyWeight: 2,
        color: '#ADFF2F',
        isBaseElement: true,
        isActive: true
    },
    {
        substanceKey: 'iron',
        type: 'element',
        name: 'Iron',
        symbol: 'Fe',
        formula: 'Fe',
        category: 'base_matter',
        generationTier: 1,
        unlockTier: 2,
        baseEnergy: 5,
        stabilityFactor: 0.9,
        reactivity: 0.5,
        fantasyWeight: 3,
        color: '#8B8682',
        hintText: 'The backbone of every tool, weapon, and machine that came after.',
        isBaseElement: true,
        isActive: true
    },
    {
        substanceKey: 'sulfur',
        type: 'element',
        name: 'Sulfur',
        symbol: 'S',
        formula: 'S',
        category: 'base_matter',
        generationTier: 1,
        unlockTier: 1,
        baseEnergy: 3,
        stabilityFactor: 0.8,
        reactivity: 0.7,
        fantasyWeight: 2,
        color: '#F5C518',
        isBaseElement: true,
        isActive: true
    },

    // ── Gen 1 — Basic Gases (3) ───────────────────────────────────────────────
    {
        substanceKey: 'hydrogen_gas',
        type: 'compound',
        name: 'Hydrogen Gas',
        symbol: 'H2',
        formula: 'H₂',
        category: 'gas',
        generationTier: 1,
        unlockTier: 0,
        baseEnergy: 3,
        stabilityFactor: 0.85,
        reactivity: 0.7,
        fantasyWeight: 1,
        color: '#E3F2FD',
        isActive: true
    },
    {
        substanceKey: 'oxygen_gas',
        type: 'compound',
        name: 'Oxygen Gas',
        symbol: 'O2',
        formula: 'O₂',
        category: 'gas',
        generationTier: 1,
        unlockTier: 0,
        baseEnergy: 5,
        stabilityFactor: 0.9,
        reactivity: 0.6,
        fantasyWeight: 1,
        color: '#FFCDD2',
        isActive: true
    },
    {
        substanceKey: 'nitrogen_gas',
        type: 'compound',
        name: 'Nitrogen Gas',
        symbol: 'N2',
        formula: 'N₂',
        category: 'gas',
        generationTier: 1,
        unlockTier: 0,
        baseEnergy: 5,
        stabilityFactor: 0.97,
        reactivity: 0.1,
        fantasyWeight: 1,
        color: '#BBDEFB',
        isActive: true
    },

    // ── Gen 1 — Compounds (6) ────────────────────────────────────────────────
    {
        substanceKey: 'water',
        type: 'compound',
        name: 'Water',
        symbol: 'H2O',
        formula: 'H₂O',
        category: 'liquid',
        generationTier: 1,
        unlockTier: 1,
        unlocksUserTier: 1,
        baseEnergy: 10,
        shardValue: 1,
        stabilityFactor: 0.95,
        reactivity: 0.3,
        fantasyWeight: 5,
        color: '#4FC3F7',
        hintText: 'The first stable molecule. Everything that follows begins here.',
        isActive: true
    },
    {
        substanceKey: 'salt',
        type: 'compound',
        name: 'Salt',
        symbol: 'NaCl',
        formula: 'NaCl',
        category: 'mineral',
        generationTier: 1,
        unlockTier: 1,
        unlocksUserTier: 2,
        shardValue: 1,
        baseEnergy: 12,
        stabilityFactor: 0.98,
        reactivity: 0.15,
        fantasyWeight: 4,
        color: '#F5F5F5',
        hintText: 'The first mineral. Civilizations rose and fell for want of it.',
        isActive: true
    },
    {
        substanceKey: 'iron_oxide',
        type: 'compound',
        name: 'Iron Oxide',
        symbol: 'Fe2O3',
        formula: 'Fe₂O₃',
        category: 'mineral',
        generationTier: 1,
        unlockTier: 1,
        unlocksUserTier: 3,
        baseEnergy: 10,
        stabilityFactor: 0.93,
        reactivity: 0.25,
        fantasyWeight: 3,
        color: '#B7410E',
        hintText: 'Rust, purified. The ore that feeds the forge.',
        isActive: true
    },
    {
        substanceKey: 'methane',
        type: 'compound',
        name: 'Methane',
        symbol: 'CH4',
        formula: 'CH₄',
        category: 'gas',
        generationTier: 1,
        unlockTier: 1,
        baseEnergy: 12,
        stabilityFactor: 0.88,
        reactivity: 0.6,
        fantasyWeight: 2,
        color: '#FFB74D',
        isActive: true
    },
    {
        substanceKey: 'ammonia',
        type: 'compound',
        name: 'Ammonia',
        symbol: 'NH3',
        formula: 'NH₃',
        category: 'gas',
        generationTier: 1,
        unlockTier: 1,
        baseEnergy: 12,
        stabilityFactor: 0.82,
        reactivity: 0.65,
        fantasyWeight: 2,
        color: '#AED581',
        isActive: true
    },
    {
        substanceKey: 'carbon_dioxide',
        type: 'compound',
        name: 'Carbon Dioxide',
        symbol: 'CO2',
        formula: 'CO₂',
        category: 'gas',
        generationTier: 1,
        unlockTier: 1,
        baseEnergy: 8,
        stabilityFactor: 0.93,
        reactivity: 0.25,
        fantasyWeight: 2,
        color: '#B0BEC5',
        isActive: true
    },

    // ── Gen 2 — The Foundry (5) ──────────────────────────────────────────────
    {
        substanceKey: 'copper',
        type: 'element',
        name: 'Copper',
        symbol: 'Cu',
        formula: 'Cu',
        category: 'metal',
        generationTier: 2,
        unlockTier: 2,
        unlocksUserTier: 4,
        baseEnergy: 15,
        stabilityFactor: 0.92,
        reactivity: 0.35,
        fantasyWeight: 4,
        color: '#B87333',
        hintText: 'First metal forged by human hands. The age of tools begins here.',
        isActive: true
    },
    {
        substanceKey: 'tin',
        type: 'element',
        name: 'Tin',
        symbol: 'Sn',
        formula: 'Sn',
        category: 'metal',
        generationTier: 2,
        unlockTier: 2,
        baseEnergy: 15,
        stabilityFactor: 0.88,
        reactivity: 0.3,
        fantasyWeight: 3,
        color: '#D3D3D3',
        isActive: true
    },
    {
        substanceKey: 'nickel',
        type: 'element',
        name: 'Nickel',
        symbol: 'Ni',
        formula: 'Ni',
        category: 'metal',
        generationTier: 2,
        unlockTier: 2,
        unlocksUserTier: 6,
        baseEnergy: 18,
        stabilityFactor: 0.93,
        reactivity: 0.28,
        fantasyWeight: 3,
        color: '#A8A9AD',
        isActive: true
    },
    {
        substanceKey: 'gold',
        type: 'element',
        name: 'Gold',
        symbol: 'Au',
        formula: 'Au',
        category: 'metal',
        generationTier: 2,
        unlockTier: 2,
        shardValue: 3,
        baseEnergy: 25,
        stabilityFactor: 0.99,
        reactivity: 0.05,
        fantasyWeight: 5,
        color: '#FFD700',
        hintText: 'The metal that never tarnishes. Rare enough to be coveted. Too soft to be useful alone.',
        isActive: true
    },
    {
        substanceKey: 'bronze',
        type: 'compound',
        name: 'Bronze',
        symbol: 'CuSn',
        formula: 'Cu·Sn',
        category: 'alloy',
        generationTier: 2,
        unlockTier: 2,
        unlocksUserTier: 5,
        shardValue: 2,
        baseEnergy: 30,
        stabilityFactor: 0.94,
        reactivity: 0.2,
        fantasyWeight: 4,
        color: '#CD7F32',
        hintText: 'Tin and copper, alloyed by fire. The first engineered material.',
        isActive: true
    },

    // ── Gen 2 — Chemical Works (3) ───────────────────────────────────────────
    {
        substanceKey: 'sulfuric_acid',
        type: 'compound',
        name: 'Sulfuric Acid',
        symbol: 'H2SO4',
        formula: 'H₂SO₄',
        category: 'acid',
        generationTier: 2,
        unlockTier: 2,
        shardValue: 2,
        baseEnergy: 28,
        stabilityFactor: 0.72,
        reactivity: 0.92,
        fantasyWeight: 4,
        color: '#E8D44D',
        hintText: 'The king of chemicals. Nothing industrial escapes its touch.',
        isActive: true
    },
    {
        substanceKey: 'nitric_acid',
        type: 'compound',
        name: 'Nitric Acid',
        symbol: 'HNO3',
        formula: 'HNO₃',
        category: 'acid',
        generationTier: 2,
        unlockTier: 2,
        baseEnergy: 25,
        stabilityFactor: 0.68,
        reactivity: 0.88,
        fantasyWeight: 3,
        color: '#FF9900',
        isActive: true
    },
    {
        substanceKey: 'quicklime',
        type: 'compound',
        name: 'Quicklime',
        symbol: 'CaO',
        formula: 'CaO',
        category: 'mineral',
        generationTier: 2,
        unlockTier: 2,
        baseEnergy: 15,
        stabilityFactor: 0.87,
        reactivity: 0.55,
        fantasyWeight: 3,
        color: '#FAFAFA',
        hintText: 'Calcium oxide. Burns hot. The precursor to concrete and glass.',
        isActive: true
    },

    // ── Gen 2 — Materials Bench (5) ──────────────────────────────────────────
    {
        substanceKey: 'quartz',
        type: 'compound',
        name: 'Quartz',
        symbol: 'SiO2',
        formula: 'SiO₂',
        category: 'mineral',
        generationTier: 2,
        unlockTier: 2,
        baseEnergy: 20,
        stabilityFactor: 0.96,
        reactivity: 0.15,
        fantasyWeight: 3,
        color: '#E0E0E0',
        hintText: 'Crystalline silicon dioxide. The raw form of both glass and semiconductor wafers.',
        isActive: true
    },
    {
        substanceKey: 'soda_ash',
        type: 'compound',
        name: 'Soda Ash',
        symbol: 'Na2CO3',
        formula: 'Na₂CO₃',
        category: 'mineral',
        generationTier: 2,
        unlockTier: 2,
        baseEnergy: 15,
        stabilityFactor: 0.91,
        reactivity: 0.3,
        fantasyWeight: 2,
        color: '#ECEFF1',
        isActive: true
    },
    {
        substanceKey: 'calcium',
        type: 'element',
        name: 'Calcium',
        symbol: 'Ca',
        formula: 'Ca',
        category: 'metal',
        generationTier: 2,
        unlockTier: 2,
        baseEnergy: 12,
        stabilityFactor: 0.78,
        reactivity: 0.7,
        fantasyWeight: 2,
        color: '#EEEEEE',
        isActive: true
    },
    {
        substanceKey: 'silicon',
        type: 'element',
        name: 'Silicon',
        symbol: 'Si',
        formula: 'Si',
        category: 'metalloid',
        generationTier: 2,
        unlockTier: 2,
        baseEnergy: 20,
        stabilityFactor: 0.95,
        reactivity: 0.4,
        fantasyWeight: 4,
        color: '#1A1A2E',
        hintText: 'Purified from sand. The foundation of every thinking machine.',
        isActive: true
    },
    {
        substanceKey: 'lithium',
        type: 'element',
        name: 'Lithium',
        symbol: 'Li',
        formula: 'Li',
        category: 'metal',
        generationTier: 2,
        unlockTier: 2,
        baseEnergy: 18,
        stabilityFactor: 0.7,
        reactivity: 0.75,
        fantasyWeight: 4,
        color: '#C8B8DB',
        hintText: 'The lightest metal. Stores charge like nothing else. The engine of the electric age.',
        isActive: true
    },

    // ── Gen 3 — The Materials Lab (9) ────────────────────────────────────────
    {
        substanceKey: 'glass',
        type: 'material',
        name: 'Glass',
        symbol: 'Glass',
        formula: 'SiO₂·Na₂O·CaO',
        category: 'advanced_material',
        generationTier: 3,
        unlockTier: 3,
        shardValue: 3,
        baseEnergy: 40,
        stabilityFactor: 0.92,
        reactivity: 0.1,
        fantasyWeight: 4,
        color: '#B2EBF2',
        hintText: 'Sand transformed by fire. Transparent windows into the material world.',
        isActive: true
    },
    {
        substanceKey: 'steel',
        type: 'material',
        name: 'Steel',
        symbol: 'Steel',
        formula: 'Fe·C',
        category: 'advanced_material',
        generationTier: 3,
        unlockTier: 3,
        unlocksUserTier: 7,
        shardValue: 4,
        baseEnergy: 50,
        stabilityFactor: 0.95,
        reactivity: 0.2,
        fantasyWeight: 5,
        color: '#607D8B',
        hintText: 'Iron, disciplined by carbon. The material that built civilization.',
        isActive: true
    },
    {
        substanceKey: 'stainless_steel',
        type: 'material',
        name: 'Stainless Steel',
        symbol: 'SSt',
        formula: 'Fe·Cr·Ni',
        category: 'advanced_material',
        generationTier: 3,
        unlockTier: 3,
        shardValue: 4,
        baseEnergy: 55,
        stabilityFactor: 0.97,
        reactivity: 0.08,
        fantasyWeight: 4,
        color: '#90A4AE',
        hintText: 'Steel that does not rust. Precision-alloyed for the modern age.',
        isActive: true
    },
    {
        substanceKey: 'chrome',
        type: 'element',
        name: 'Chrome',
        symbol: 'Cr',
        formula: 'Cr',
        category: 'metal',
        generationTier: 3,
        unlockTier: 3,
        unlocksUserTier: 8,
        baseEnergy: 45,
        stabilityFactor: 0.96,
        reactivity: 0.15,
        fantasyWeight: 3,
        color: '#E0E0E0',
        isActive: true
    },
    {
        substanceKey: 'graphene',
        type: 'material',
        name: 'Graphene',
        symbol: 'Grph',
        formula: 'C (monolayer)',
        category: 'advanced_material',
        generationTier: 3,
        unlockTier: 3,
        unlocksUserTier: 9,
        shardValue: 5,
        baseEnergy: 70,
        stabilityFactor: 0.99,
        reactivity: 0.05,
        fantasyWeight: 4,
        color: '#212121',
        hintText: 'A single layer of carbon atoms. Stronger than steel. Thinner than thought.',
        isActive: true
    },
    {
        substanceKey: 'carbon_nanotube',
        type: 'material',
        name: 'Carbon Nanotube',
        symbol: 'CNT',
        formula: 'C (nanotube)',
        category: 'advanced_material',
        generationTier: 3,
        unlockTier: 3,
        shardValue: 5,
        baseEnergy: 80,
        stabilityFactor: 0.98,
        reactivity: 0.06,
        fantasyWeight: 4,
        color: '#1A1A1A',
        hintText: 'Graphene, rolled into a tube. An almost impossible structure that actually exists.',
        isActive: true
    },
    {
        substanceKey: 'aramid_fiber',
        type: 'material',
        name: 'Aramid Fiber',
        symbol: 'ARF',
        formula: 'C₁₄H₁₀N₂O₂ (n)',
        category: 'advanced_material',
        generationTier: 3,
        unlockTier: 3,
        shardValue: 4,
        baseEnergy: 65,
        stabilityFactor: 0.96,
        reactivity: 0.05,
        fantasyWeight: 3,
        color: '#FDD835',
        hintText: 'Woven from nitrogen-linked rings. Five times stronger than steel at a fraction of the weight.',
        isActive: true
    },
    {
        substanceKey: 'doped_silicon',
        type: 'material',
        name: 'Doped Silicon',
        symbol: 'Si:Au',
        formula: 'Si·Au',
        category: 'advanced_material',
        generationTier: 3,
        unlockTier: 3,
        shardValue: 4,
        baseEnergy: 60,
        stabilityFactor: 0.97,
        reactivity: 0.1,
        fantasyWeight: 4,
        color: '#283593',
        hintText: 'Silicon laced with gold. A reactor-temperature process that bends the rules of conductivity.',
        isActive: true
    },
    {
        substanceKey: 'lithium_ion_cell',
        type: 'material',
        name: 'Lithium Ion Cell',
        symbol: 'LiCell',
        formula: 'LiCoO₂',
        category: 'advanced_material',
        generationTier: 3,
        unlockTier: 3,
        unlocksUserTier: 10,
        shardValue: 6,
        baseEnergy: 90,
        stabilityFactor: 0.88,
        reactivity: 0.3,
        fantasyWeight: 5,
        color: '#43A047',
        hintText: 'Charge and discharge, cycle after cycle. The heart of portable power.',
        isActive: true
    }
];

// Expected: 18 Gen 1 + 13 Gen 2 + 9 Gen 3 = 40 total
const gen1 = substances.filter(s => s.generationTier === 1).length;
const gen2 = substances.filter(s => s.generationTier === 2).length;
const gen3 = substances.filter(s => s.generationTier === 3).length;
console.assert(gen1 === 18, `Gen 1 count wrong: ${gen1}`);
console.assert(gen2 === 13, `Gen 2 count wrong: ${gen2}`);
console.assert(gen3 === 9,  `Gen 3 count wrong: ${gen3}`);

(async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);

        let inserted = 0, updated = 0;
        for (const sub of substances) {
            const result = await Substance.updateOne(
                { substanceKey: sub.substanceKey },
                { $set: sub },
                { upsert: true }
            );
            if (result.upsertedCount) inserted++;
            else if (result.modifiedCount) updated++;
        }

        // Stale-content report — does NOT delete anything
        const seededKeys = substances.map(s => s.substanceKey);
        const stale = await Substance.find({ substanceKey: { $nin: seededKeys } }, 'substanceKey _id');
        if (stale.length > 0) {
            console.warn(`Stale substances not in seed (${stale.length}) — not deleted:`);
            stale.forEach(s => console.warn(`  substanceKey: '${s.substanceKey}'  _id: ${s._id}`));
        }

        console.log(`Substances: ${inserted} inserted, ${updated} updated, ${substances.length - inserted - updated} unchanged.`);
    }
    catch (err) {
        console.log(err);
    }
    finally {
        mongoose.disconnect();
    }
})();
